load('//:subdir_glob.bzl', 'subdir_glob')

cxx_library(
  name = 'juce_opengl',
  header_namespace = '',
  exported_headers = subdir_glob([
    ('', '**/*.h'),
  ], prefix = 'juce_opengl'),
  headers = glob([
    '*/**/*.cpp',
    '*/**/*.mm',
  ]),
  srcs = [
    'juce_opengl.cpp',
  ],
  deps = [
    '//modules/juce_gui_extra:juce_gui_extra',
  ],
  visibility = [
    'PUBLIC',
  ],
)
