load('//:subdir_glob.bzl', 'subdir_glob')

cxx_library(
  name = 'juce_product_unlocking',
  header_namespace = '',
  exported_headers = subdir_glob([
    ('', '**/*.h'),
  ], prefix = 'juce_product_unlocking'),
  headers = glob([
    '*/**/*.cpp',
    '*/**/*.mm',
  ]),
  srcs = [
    'juce_product_unlocking.cpp',
  ],
  deps = [
    '//modules/juce_core:juce_core',
    '//modules/juce_cryptography:juce_cryptography',
  ],
  visibility = [
    'PUBLIC',
  ],
)
